#!/usr/bin/env node
// Regenerates content.generated.js from the Markdown files in content/.
// Usage: node build-content.js
// - Add/edit topics: content/<category>/<NN>-<slug>.md
// - Add/edit themes: content/themes.md

const fs = require("fs");
const path = require("path");

const CONTENT_DIR = path.join(__dirname, "content");
const THEMES_FILE = path.join(CONTENT_DIR, "themes.md");
const OUTPUT_FILE = path.join(__dirname, "content.generated.js");
const CATEGORY_ORDER = ["starters", "mains", "dessert"];
const LANGS = ["ja", "de", "en"];

function parseThemes(text) {
  const lines = text.replace(/\r\n/g, "\n").split("\n");
  const themes = [];
  let current = null;

  for (const line of lines) {
    const heading = line.match(/^##\s+([a-z0-9-]+)\s*$/i);
    if (heading) {
      current = { key: heading[1].toLowerCase(), title: {} };
      themes.push(current);
      continue;
    }
    const field = line.match(/^(ja|de|en):\s*(.+)$/i);
    if (field && current) {
      current.title[field[1].toLowerCase()] = field[2].trim();
    }
  }

  for (const theme of themes) {
    for (const lang of LANGS) {
      if (!theme.title[lang]) {
        throw new Error(`content/themes.md: theme "${theme.key}" is missing a "${lang}:" label`);
      }
    }
  }
  return themes;
}

function parseMarkdown(text, filePath) {
  const lines = text.replace(/\r\n/g, "\n").split("\n");
  const sections = {};
  const tags = [];
  let currentLang = null;

  for (const line of lines) {
    const heading = line.match(/^##\s+(ja|de|en)\s*$/i);
    if (heading) {
      currentLang = heading[1].toLowerCase();
      sections[currentLang] = [];
      continue;
    }
    if (currentLang) {
      sections[currentLang].push(line);
      continue;
    }
    const tagsLine = line.match(/^tags:\s*(.+)$/i);
    if (tagsLine) {
      tags.push(
        ...tagsLine[1]
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean)
      );
    }
  }

  const result = { tags };
  for (const lang of LANGS) {
    const contentLines = (sections[lang] || []).map((l) => l.trim());
    const firstNonEmpty = contentLines.findIndex((l) => l.length > 0);
    if (firstNonEmpty === -1) {
      throw new Error(`${filePath}: missing "## ${lang}" section with content`);
    }
    const title = contentLines[firstNonEmpty];
    const desc = contentLines
      .slice(firstNonEmpty + 1)
      .filter((l) => l.length > 0)
      .join(" ");
    if (!desc) {
      throw new Error(`${filePath}: "## ${lang}" section is missing a description paragraph`);
    }
    result[lang] = { title, desc };
  }
  return result;
}

function buildMenuItems(validThemeKeys) {
  const items = [];

  for (const category of CATEGORY_ORDER) {
    const categoryDir = path.join(CONTENT_DIR, category);
    if (!fs.existsSync(categoryDir)) continue;

    const files = fs
      .readdirSync(categoryDir)
      .filter((f) => /^\d+-.*\.md$/.test(f))
      .sort();

    for (const file of files) {
      const filePath = path.join(categoryDir, file);
      const relPath = path.relative(__dirname, filePath);
      const slug = file.replace(/\.md$/, "").replace(/^\d+-/, "");
      const parsed = parseMarkdown(fs.readFileSync(filePath, "utf8"), relPath);

      for (const tag of parsed.tags) {
        if (!validThemeKeys.has(tag)) {
          throw new Error(`${relPath}: unknown theme "${tag}" (not defined in content/themes.md)`);
        }
      }

      items.push({
        id: `${category}-${slug}`,
        category,
        tags: parsed.tags,
        title: { ja: parsed.ja.title, de: parsed.de.title, en: parsed.en.title },
        desc: { ja: parsed.ja.desc, de: parsed.de.desc, en: parsed.en.desc },
      });
    }
  }

  return items;
}

function main() {
  const themes = fs.existsSync(THEMES_FILE)
    ? parseThemes(fs.readFileSync(THEMES_FILE, "utf8"))
    : [];
  const validThemeKeys = new Set(themes.map((t) => t.key));
  const items = buildMenuItems(validThemeKeys);

  const banner = [
    "// AUTO-GENERATED by build-content.js — do not edit this file directly.",
    "// Edit the .md files in content/ instead, then run: node build-content.js",
    "",
  ].join("\n");
  const body =
    `const THEMES = ${JSON.stringify(themes, null, 2)};\n\n` +
    `const MENU_ITEMS = ${JSON.stringify(items, null, 2)};\n`;

  fs.writeFileSync(OUTPUT_FILE, banner + body);
  console.log(
    `Wrote ${themes.length} themes and ${items.length} menu items to ${path.relative(__dirname, OUTPUT_FILE)}`
  );
}

main();
