const UI_TEXT = {
  ja: {
    siteTitle: "日本学 情報リテラシー メニュー",
    siteIntro: "気になるトピックを選んで「注文する」を押してください。選んでいただいた内容について、個別にご相談・レクチャーの機会を設けます。",
    addLabel: "追加する",
    addedLabel: "追加済み ✓",
    orderCountLabel: "選択中: {n} 件",
    orderButtonLabel: "注文する",
    orderEmptyHint: "気になるメニューを選んでください",
    footerNote: "ご質問・ご相談はお気軽にどうぞ。",
    mailSubject: "情報リテラシー相談のご依頼",
    mailBodyIntro: "以下のトピックについて相談を希望します。",
    mailBodyName: "お名前:",
    mailBodyAffiliation: "所属:",
    mailBodyPreferredTime: "ご希望の日時:",
    searchPlaceholder: "キーワードで検索",
    facetSummary: "テーマで絞り込む",
    noResultsText: "該当するメニューが見つかりません。",
    showMoreLabel: "もっと見る",
    showLessLabel: "閉じる",
  },
  de: {
    siteTitle: "Informationskompetenz für die Japanologie",
    siteIntro: "Wählen Sie die Themen aus, die Sie interessieren, und klicken Sie auf «Bestellen». Zu den ausgewählten Themen biete ich Ihnen gerne eine individuelle Beratung an.",
    addLabel: "Hinzufügen",
    addedLabel: "Hinzugefügt ✓",
    orderCountLabel: "{n} ausgewählt",
    orderButtonLabel: "Bestellen",
    orderEmptyHint: "Bitte wählen Sie mindestens ein Thema",
    footerNote: "Fragen und Beratungswünsche sind jederzeit willkommen.",
    mailSubject: "Anfrage: Beratung Informationskompetenz",
    mailBodyIntro: "Ich interessiere mich für eine Beratung zu folgenden Themen:",
    mailBodyName: "Name:",
    mailBodyAffiliation: "Institution:",
    mailBodyPreferredTime: "Terminwunsch:",
    searchPlaceholder: "Stichwort suchen",
    facetSummary: "Nach Thema filtern",
    noResultsText: "Keine passenden Themen gefunden.",
    showMoreLabel: "Mehr anzeigen",
    showLessLabel: "Weniger anzeigen",
  },
  en: {
    siteTitle: "Information Literacy for Japanese Studies",
    siteIntro: "Pick the topics that interest you and click \"Order\". I'll get in touch to arrange an individual consultation covering exactly what you selected.",
    addLabel: "Add",
    addedLabel: "Added ✓",
    orderCountLabel: "{n} selected",
    orderButtonLabel: "Order",
    orderEmptyHint: "Please select at least one topic",
    footerNote: "Questions and consultation requests are always welcome.",
    mailSubject: "Consultation request: Information literacy",
    mailBodyIntro: "I would like to request a consultation on the following topics:",
    mailBodyName: "Name:",
    mailBodyAffiliation: "Affiliation:",
    mailBodyPreferredTime: "Preferred date/time:",
    searchPlaceholder: "Search keywords",
    facetSummary: "Filter by theme",
    noResultsText: "No matching topics found.",
    showMoreLabel: "Show more",
    showLessLabel: "Show less",
  },
};

const CATEGORIES = [
  {
    key: "starters",
    icon: "🥗",
    title: { ja: "前菜", de: "Vorspeisen", en: "Starters" },
    subtitle: {
      ja: "リサーチの基本",
      de: "Recherche-Grundlagen",
      en: "Research basics",
    },
  },
  {
    key: "mains",
    icon: "🍚",
    title: { ja: "主食", de: "Hauptgang", en: "Mains" },
    subtitle: {
      ja: "資料とデータを深く探す",
      de: "Ressourcen & Daten vertiefen",
      en: "Deeper resource & data discovery",
    },
  },
  {
    key: "dessert",
    icon: "🍡",
    title: { ja: "デザート", de: "Dessert", en: "Dessert" },
    subtitle: {
      ja: "デジタル人文学とAI活用",
      de: "Digital Humanities & KI",
      en: "Digital humanities & AI",
    },
  },
];

// MENU_ITEMS lives in menu-items.generated.js (built from content/*.md by build-content.js).
